Implement business
reckyy/mokumoku pull request #3
Opened 2023-03-05 10:24 UTC by reckyy

お世話になっております。
実装完了しました。ご査収の程、よろしくお願いいたします。

### 選択した事業課題
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？
***

テストのスクリーンショットを以下に添付します。

![](https://i.gyazo.com/912318fce52194f63b77b01a1c064d87.png)

2023-03-05 23:43 UTC, busitora requested changes
コメントしました！

2023-03-05 23:43 UTC, busitora commented on app/views/events/_form.html.erb
> +  <% if current_user.gender == "woman" %>
== ではなく woman? のように評価できるよう変更をおねがいします。

2023-03-09 11:43 UTC, reckyy commented
返信遅くなり、申し訳ありません。
修正致しましたので、ご確認いただけますと幸いです。
よろしくお願いいたします！

2023-03-09 12:05 UTC, busitora requested changes

2023-03-09 12:05 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% if current_user.gender == "woman" %>
こちらも woman? にできませんか？

2023-03-11 00:12 UTC, reckyy commented
申し訳ございません。
該当箇所も修正致しましたので、ご確認いただけますと幸いです。
よろしくお願いいたします！

2023-03-11 02:31 UTC, masa-oh commented
確認しました！LGTMです！🎉

2023-03-11 09:45 UTC, reckyy commented
ありがとうございます！

2023-03-11 09:46 UTC, merged